# Generated by Django 5.1 on 2024-10-02 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_remove_reciperequirement_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 2, 11, 56, 2, 265824)),
        ),
    ]
