# Generated by Django 5.1 on 2024-10-09 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_alter_purchase_purchase_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciperequirement',
            old_name='ingredients',
            new_name='ingredient',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 12, 59, 28, 515166)),
        ),
    ]
