# Generated by Django 5.1 on 2024-10-09 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0017_alter_purchase_purchase_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='revenue',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 18, 23, 34, 982458)),
        ),
    ]
