# Generated by Django 5.1 on 2024-10-10 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0018_menuitem_revenue_alter_purchase_purchase_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_purchases', models.FloatField(default=0.0)),
                ('total_cost', models.FloatField(default=0.0)),
                ('total_revenue', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 10, 19, 14, 24, 897471)),
        ),
        migrations.DeleteModel(
            name='Calculates',
        ),
    ]
