# Generated by Django 5.1 on 2024-10-10 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0019_daysummary_alter_purchase_purchase_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 10, 19, 28, 42, 180154)),
        ),
    ]
