# Generated by Django 5.1 on 2024-10-14 11:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0025_alter_day_date_alter_purchase_purchase_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='day',
            name='purchases',
        ),
        migrations.RemoveField(
            model_name='day',
            name='summary',
        ),
        migrations.AddField(
            model_name='day',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.day'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 14, 47, 52, 319830)),
        ),
    ]
