# Generated by Django 5.1 on 2024-10-14 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0026_remove_day_inventory_remove_day_purchases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 18, 52, 25, 791318)),
        ),
    ]
