# Generated by Django 5.1 on 2024-10-22 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0042_day_today_ingredients_alter_purchase_purchase_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DaySummary',
        ),
        migrations.AddField(
            model_name='day',
            name='num_purchases',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='day',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='day',
            name='total_revenue',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='day',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 22, 12, 15, 52, 46415)),
        ),
    ]
