# Generated by Django 5.1 on 2024-11-07 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0044_alter_purchase_purchase_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='start_quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 19, 23, 20, 860664)),
        ),
    ]
