# Generated by Django 5.1 on 2024-11-07 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0045_ingredient_start_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 23, 23, 12, 270556)),
        ),
    ]
