# Generated by Django 5.1 on 2024-11-08 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0047_alter_purchase_purchase_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='quantity_to_purchase',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 9, 11, 59, 737314)),
        ),
    ]
