# Generated by Django 5.1 on 2024-11-08 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0048_ingredient_quantity_to_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 9, 17, 50, 428161)),
        ),
    ]
